# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import chatapp_pb2 as chatapp__pb2


class ChatAppStub(object):
    """Interface exported by the chat server
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Send = channel.unary_unary(
                '/ChatApp/Send',
                request_serializer=chatapp__pb2.Request.SerializeToString,
                response_deserializer=chatapp__pb2.Response.FromString,
                )
        self.Listen = channel.unary_unary(
                '/ChatApp/Listen',
                request_serializer=chatapp__pb2.Request.SerializeToString,
                response_deserializer=chatapp__pb2.Responses.FromString,
                )


class ChatAppServicer(object):
    """Interface exported by the chat server
    """

    def Send(self, request, context):
        """Send request to server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Listen(self, request, context):
        """Listen to server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatAppServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Send': grpc.unary_unary_rpc_method_handler(
                    servicer.Send,
                    request_deserializer=chatapp__pb2.Request.FromString,
                    response_serializer=chatapp__pb2.Response.SerializeToString,
            ),
            'Listen': grpc.unary_unary_rpc_method_handler(
                    servicer.Listen,
                    request_deserializer=chatapp__pb2.Request.FromString,
                    response_serializer=chatapp__pb2.Responses.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ChatApp', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ChatApp(object):
    """Interface exported by the chat server
    """

    @staticmethod
    def Send(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ChatApp/Send',
            chatapp__pb2.Request.SerializeToString,
            chatapp__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Listen(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ChatApp/Listen',
            chatapp__pb2.Request.SerializeToString,
            chatapp__pb2.Responses.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
